// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// clipper-cpp11.h
writable::integers cpp_pip(const list layer, const list xy);
extern "C" SEXP _naturoute_cpp_pip(SEXP layer, SEXP xy) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_pip(cpp11::as_cpp<cpp11::decay_t<const list>>(layer), cpp11::as_cpp<cpp11::decay_t<const list>>(xy)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_naturoute_cpp_pip", (DL_FUNC) &_naturoute_cpp_pip, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_naturoute(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
